### ISSUE TITLE
ERROR, can not convert non-pacbio reads to pbbam record.

### ISSUE THREAD

**Issue by svm-zhang** [PacificBiosciences/blasr#312] opened 2016-12-13 22:16 UTC
Hello,

I have a set of preassembled reads that I'd like to align them back to an assembly using Blasr. The following is my command line:

`blasr preads.fasta assembly.fa --nproc 16 --minMatch 18 --sam --out test.sam`

And I got the "ERROR, cannot convert non-pacbio reads to pbbam record". The Blasr version I used is: `5.3.8c16f52`. Blasr was installed using pitchfork.

It looks like the error was complaining about the reads in FASTA format. And the help message says after v5.2 --sam is no longer supported. In this case, could you please tell me which version of blasr I should be using? Go back to the version built in smrtpipe 2.3.0? Or there is some other versions available that supports this old way?

Thanks for any help!

Simo

**Comment by afif-elghraoui** [comment] 2016-12-23 08:42
Yes, is there a way to have sam/bam output with fasta/fastq input? I'm trying to fix pbhoney to work with blasr 5 (https://sourceforge.net/p/pb-jelly/tickets/5/), but I can't test it properly because of this. There is no need for extensive QV data for pbhoney, so it would be great if blasr wouldn't require this for sam/bam output.

**Comment by ylipacbio** [comment] 2016-12-23 23:13
Please use pitchfork to install `legacy_blasr`, which supports sam output from generic fasta input.

```
git clone git@github.com:PacificBiosciences/pitchfork.git
cd pitchfork
make init
make legacy_blasr PREFIX=/opt/mybuild             # if you want to build your own blasr
bash --init-file /opt/mybuild/setup-env.sh # either to use the build in the sub-shell
source /opt/mybuild/setup-env.sh           # or     to use the build in current shell 
```

Or alternatively, you may change read name to pacbio compatible format movie/zmw/start_end, e.g., 
change 
```
>read
AAAAAAAAAA
```
to 
```
>read/0/0_10
AAAAAAAAAA
```

**Comment by ylipacbio** [comment] 2016-12-23 23:14
Will consider support generating sam/bam output for generic fasta input.

**Comment by afif-elghraoui** [comment] 2016-12-23 23:36
> Please use pitchfork to install legacy_blasr, which supports sam output from generic fasta input.

And this version has many of the bugs that are fixed in the current version?

> Or alternatively, you may change read name to pacbio compatible format movie/zmw/start_end

This doesn't work. The [fastq file I'm testing with](https://sourceforge.net/p/pb-jelly/code-0/HEAD/tree/trunk/docs/honeyExample/filtered_subreads.fastq) already has its headers in this format. I believe it's the direct fastq output from SMRTPortal filtering.

> Will consider support generating sam/bam output for generic fasta input.

I think this would be the only feasible solution.

**Comment by ylipacbio** [comment] 2016-12-24 00:08
I @afif-elghraoui, I was able to successfully map the first few records in the test case that you have provided to ecoli using blasr.

```
blasr --version
blasr   5.3.8d086d7

blasr tiny.fq ecoli.fa --sam --out out.sam  --nproc 10
ls out.sam
```

**Comment by afif-elghraoui** [comment] 2016-12-24 00:14
There were several things I tried a couple days ago. While I could get *a* SAM or BAM file, samtools had trouble with it. I couldn't get it to add headers, so then when I called blasr with both `--sam` and `--header` I'd get this error:

```
2016-12-23 08:09:49,660 [INFO] Running Blasr
2016-12-23 08:09:50,161 [ERROR] blasr mapping failed!
2016-12-23 08:09:50,162 [ERROR] RETCODE 255
2016-12-23 08:09:50,162 [ERROR] STDOUT [INFO] 2016-12-23T08:09:49 [blasr] started.
ERROR, can not convert non-pacbio reads to pbbam record.

2016-12-23 08:09:50,162 [ERROR] STDERR None
2016-12-23 08:09:50,163 [ERROR] Exiting
```

I can collect more detailed information and report back.

**Comment by ylipacbio** [comment] 2016-12-24 00:15
Please provide blasr version, I think this can be solved by upgrading blasr to the latest version.

`blasr --version`

**Comment by afif-elghraoui** [comment] 2016-12-24 00:26
This was with 5.3 at snapshot 1baabc8. I'll try again with the version you just tagged. Many thanks

**Comment by svm-zhang** [comment] 2016-12-24 17:12
@ylipacbio does this mean as of now, I can only use the legacy_blasr to map reads in FASTA? Does this legacy version different from the one built in SMRT2.3.0?

If I change read names, does it matter what I give to movie/zmw/start_end?

Thanks,
Simo

**Comment by afif-elghraoui** [comment] 2016-12-24 20:39
@ylipacbio, upgrading to the new version didn't help. However, you were right about the fast{a,q} headers. It turns out that pbhoney writes intermediate fastq files with mapping information appended to the original headers. When it tries to map these files using blasr, I get the error I mentioned above.

That will need some more intrusive patching to pbhoney, but I still agree that the fasta header shouldn't be required to be in a specific format.

Thanks for all your help.

**Comment by afif-elghraoui** [comment] 2016-12-29 06:01
> If I change read names, does it matter what I give to movie/zmw/start_end?

@svm-zhang, I don't think so. I've changed the "movie" part and it didn't make a difference.

**Comment by svm-zhang** [comment] 2016-12-30 03:06
@afif-elghraoui Thanks! 

Now just need to know what's the differences between legacy_blasr and the one built in smrtanalysis 2.3.0, since you mentioned bugs in the legacy version.

**Comment by afif-elghraoui** [comment] 2016-12-30 05:18
> Now just need to know what's the differences between legacy_blasr and the one built in smrtanalysis 2.3.0, since you mentioned bugs in the legacy version.

Why? If you change your fasta headers to fool blasr 5.3, you can use that now. There are always bugs, but the newer version is known to have fixed bugs that exist in older versions (in the normal course of progress).

You can change your fasta headers like this:
```
sed 's|\(^>\S*\)|\1/0/0_10|' preads.fasta > preads.issue-312-workaround.fasta
```
and see if it will work.

**Comment by svm-zhang** [comment] 2016-12-30 17:34
@afif-elghraoui ahh, I misread all the previous threads. Let me change my read name and try again! Thanks!

**Comment by ylipacbio** [comment] 2017-01-03 19:30
@svm-zhang 
>does this mean as of now, I can only use the legacy_blasr to map reads in FASTA? Does this legacy version different from the one built in SMRT2.3.0?

You can use either legacy blasr or latest blasr to map generic reads in FASTA file to reference. However,

- taking a generic fasta file as input, legacy blasr allows to generate a generic SAM output, which does not conform to pacbio SAM/BAM specification
* taking a generic fasta file as input, latest blasr DOES NOT allow to generate SAM/BAM output, but it can generate other types of output, including m0, m1, m2, m3, m4 and m5 (i.e., via option  '-m 5')
* taking a PacBio fasta file as input (where read names in a PacBio fasta file must conform to 'movie/zmw/start_end' format, latest blasr allows to generate PacBio SAM and BAM output (which conforms to PacBio BAM specifications)


Also SAM output produced by legacy blasr and latest blasr are not compatible, because cigar strings and many tags are different.

**Comment by ylipacbio** [comment] 2017-01-05 22:12
Also explained in FAQ: https://github.com/PacificBiosciences/blasr/wiki/BLASR-Frequently-Asked-Questions#why-i-see-error-message-error-can-not-convert-non-pacbio-reads-to-pbbam-record

**Closed by ylipacbio** 2017-01-05 22:12 UTC

**Comment by svm-zhang** [comment] 2017-01-06 23:51
@ylipacbio @afif-elghraoui I was able to confirm that latest BLASR works with renamed Fasta files. Thanks!

**Comment by splaisan** [comment] 2017-03-03 13:37
The fix does not work for me after changing (example first record)

```
>m141129_125831_42161_c100698142550000001823143403261592_s1_p0/157569/1692_67_CCS strand=-;fiveseen=1;polyAseen=1;threeseen=1;fiveend=39;polyAend=1664;th
reeend=1701;primer=1;chimera=0
```
to

```>m141129_125831_42161_c100698142550000001823143403261592_s1_p0/157569/1692_67_CCS/0/0_10 strand=-;fiveseen=1;polyAseen=1;threeseen=1;fiveend=39;polyAend=1664;th
reeend=1701;primer=1;chimera=0
```

**Comment by afif-elghraoui** [comment] 2017-03-04 19:06
Your headers already had forward-slashes in them (which I didn't consider in my command) and was already sort of in PacBio format, but it looks like you figured it out.

If the header doesn't conform to PacBio standard, it should just emit a warning--this wouldn't need the adding of an option. You could even do a similar, more generalized `sed` operation internally if you are holding yourselves to the capabilities of `pbbam`.

**Comment by splaisan** [comment] 2017-03-06 08:14
More than 'sort of in PacBio format', it was a direct output from a SMRT-Link v4 IsoSeq analysis. My modified sed command takes care of the secondary header field (after a space) in such file and works just fine. Only wanted to point out the issue is with proprietary PB data. I believe that Users generating data with non PB tools or other PB tools with non-uniform standards and coming back with the resulting FastA would really be happy with a command that supports all kind of FastA.
Thanks for your support.
